theme: jekyll-theme-architect
title: Camp Sci
description: Welcome Campers!
show_downloads: false


defaults:
  -
    scope:
    path: ""
    type: ""
    values:
    layout: "default"
  -
    scope:
    path: "posts"
    type: "posts"
    values: 
    layout: "post"
    author: "Camille Camejo"
  -
    scope:
    path: "projects"
    type: "pages"
    values:
    layout: "projcet"
    author: "Mr. Hyde"
